### ISSUE TITLE
ImmortalCoordinator can't yet run in ambrosia image instead of ambrosia-dev

### ISSUE THREAD

**Issue by rrnewton** [Microsoft/AMBROSIA#3]
In ambrosia-dev things work fine, but in the image that contains only the binaries (`ambrosia/bin`), I'm seeing this error when I start the coordinator:

```root@031991ca3383:/ambrosia/bin# ./ImmortalCoordinator -i native1 -p 1500
Starting CRA Worker instance [http://github.com/Microsoft/CRA]
   Instance Name: native10
   IP address: 172.17.0.2
   Port: 1500
   Azure connection string: xxxxxxxx
   Secure network connections: Disabled
Disabling dynamic assembly loading
Enabling sideload for vertex: ambrosia (Ambrosia.AmbrosiaRuntime)

Unhandled Exception: System.AggregateException: One or more errors occurred. (The type initializer for 'System.Net.Http.CurlHandler' threw an exc

eption.) ---> System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> System.TypeInit

ializationException: The type initializer for 'Http' threw an exception. ---> System.TypeInitializationException: The type initializer for 'HttpI

nitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Net.Http.Native': The specified module or one of its

 dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.Http.GetSslVersionDescription()
   at Interop.HttpInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http.GetSupportedFeatures()
   at System.Net.Http.CurlHandler..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Http.CurlHandler..ctor()
   at System.Net.Http.HttpClientHandler..ctor()
   at Microsoft.WindowsAzure.Storage.Auth.Protocol.StorageAuthenticationHttpHandler.<>c.<.cctor>b__9_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpClientFactory.<>c.<.cctor>b__3_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.CreateValue()
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsyncInternal>d__4`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at CRA.ClientLibrary.VertexTableManager.RegisterInstance(String instanceName, String address, Int32 port)
   at CRA.ClientLibrary.CRAWorker.Start()
   at CRA.Worker.Program.Main(String[] args) in /ambrosia/ImmortalCoordinator/Program.cs:line 101
Aborted```

As you can see that happens even when running it inside the directory *with* all those dependency dll's that `dotnet publish` put there.

**Comment by rrnewton** [comment]
Commit 17fab278ba30555a611f94c198228d28667ae2e4 was an attempt to address this.  Let's see if it worked.

**Comment by rrnewton** [comment]
Works fine now.
