### ISSUE TITLE
Samples: ActiveActive windows throwing exception

### ISSUE THREAD

**Issue by jjr2527** [microsoft/AMBROSIA#96]
**When I come to the following command:**
To run the Immortal Coordinator for the first server replica

```
cd %AMBROSIATOOLS%\x64\Release\netcoreapp2.0
dotnet ImmortalCoordinator.dll -instanceName=server -port=3500 -r=1
```

**I am getting the following error:**
```
Starting CRA Worker instance [http://github.com/Microsoft/CRA]
   Instance Name: server1
   IP address: 10.9.137.26
   Port: 3500
   Azure connection string: my_conn_str
   Secure network connections: Disabled
Disabling dynamic assembly loading
Enabling sideload for vertex: ambrosia (Ambrosia.AmbrosiaRuntime)
Ready ...
Logs directory: C:\logs\
INFO: Unable to initialize vertex server. Check if runtime is compatible (uploaded vertex and worker should be same .NET runtime). Exception:
System.AggregateException: One or more errors occurred. (An attempt was made to access a socket in a way forbidden by its access permissions) ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Ambrosia.AmbrosiaRuntime.SetupLocalServiceStreams() in D:\a\1\s\Ambrosia\Ambrosia\Program.cs:line 2156
   at Ambrosia.AmbrosiaRuntime.PrepareToRecoverOrStart() in D:\a\1\s\Ambrosia\Ambrosia\Program.cs:line 2212
   at Ambrosia.AmbrosiaRuntime.<RecoverOrStartAsync>d__91.MoveNext() in D:\a\1\s\Ambrosia\Ambrosia\Program.cs:line 2254
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Ambrosia.AmbrosiaRuntime.Initialize(Int32 serviceReceiveFromPort, Int32 serviceSendToPort, String serviceName, String serviceLogPath, Nullable`1 createService, Boolean pauseAtStart, Boolean persistLogs, Boolean activeActive, Int64 logTriggerSizeMB, String storageConnectionString, Int64 currentVersion, Int64 upgradeToVersion) in D:\a\1\s\Ambrosia\Ambrosia\Program.cs:line 3845
   at Ambrosia.AmbrosiaRuntime.Initialize(Object param) in D:\a\1\s\Ambrosia\Ambrosia\Program.cs:line 3742
   at CRA.ClientLibrary.CRAClientLibrary.<InitializeVertexAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CRA.ClientLibrary.CRAClientLibrary.<LoadVertexAsync>d__38.MoveNext()
---> (Inner Exception #0) System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Ambrosia.AmbrosiaRuntime.SetupLocalServiceStreams() in D:\a\1\s\Ambrosia\Ambrosia\Program.cs:line 2156
   at Ambrosia.AmbrosiaRuntime.PrepareToRecoverOrStart() in D:\a\1\s\Ambrosia\Ambrosia\Program.cs:line 2212
   at Ambrosia.AmbrosiaRuntime.<RecoverOrStartAsync>d__91.MoveNext() in D:\a\1\s\Ambrosia\Ambrosia\Program.cs:line 2254<---

```

Windows 10

**Comment by jongoldDB** [comment]
It looks like the users port wasn't available for use. Note that unique ports are needed for each replica

**Comment by jjr2527** [comment]
I thought that might be the case so I tried many different port numbers without any luck.  I continued to get the same error.
